#----------------------------------
# Manifest File to create Single Container Pod Deployment
# with LoadBalancer Service
#----------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: apache-test
  labels:
    created_by: mtimoshchenko
    app_name  : apache2
    env       : test
spec:
  replicas: 3
  selector:
    matchLabels:
      project: test-gh-action
  template:
    metadata:
      labels:
        project: test-gh-action  # Service will look for those PODS Label!!!
    spec:
      containers:
        - name : apache-container
          image: mtimoshchenko/mtim-test-ghact:0.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    created_by: mtimoshchenko
    app_name  : autoscaller
    env       : test
spec:
  selector:
    project: test-gh-action    # Selecting PODS those Labels
  ports:
    - name      : apache-listener
      protocol  : TCP
      port      : 80           # Port on LoadBalancer
      targetPort: 80           # Port on POD
  type: LoadBalancer