apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : apache-test
  region: us-east-1

nodeGroups:
  - name           : worker-nodes-group-1
    instanceType   : t2.small
    desiredCapacity: 2
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c']