# This is a basic workflow to help you get started with Actions

name: Deploy httpd in EKS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Build httpd container image
        run: |
          docker build ./ -t mtimoshchenko/mtim-test-ghact:0.2
          
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}  
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          
      - name: Push image to DockerHub
        run: |
          docker push mtimoshchenko/mtim-test-ghact:0.2
