output "region" {
  description = "AWS region."
  value       = lookup(var.global_parameters, "aws_region", null)
}

output "vpc_id" {
  description = "VPC ID."
  value       = module.vpc.vpc_id
}

output "public_subnets" {
  description = "List of public subnets."
  value       = module.vpc.public_subnets
}

output "private_subnets" {
  description = "List of private subnets."
  value       = module.vpc.private_subnets
}

//output "sg_id" {
//  description = "Security group ID."
//  value       = module.sg.sg_id.this_security_group_id
//}

output "cluster_endpoint" {
  description = "EKS cluster endpoint."
  value       = module.eks.cluster_endpoint
}

output "cluster_sg_id" {
  description = "Security group ids attached to the cluster."
  value       = module.eks.cluster_sg_id
}

output "node_groups" {
  description = "Outputs from node groups."
  value       = module.eks.node_groups
}

////output "kubectl_config" {
////  description = "kubectl config as generated by the module."
////  value       = module.eks.kubeconfig
////}
//
